query globalGeneral($siteId: [QueryArgument]!) {
  globalGeneralEntries(siteId: $siteId) {
    ... on globalGeneral_globalGeneral_Entry {
      fieldTermsPage {
        uri
      }
      fieldPP {
        uri
      }
    }
  }
}
