query topNav($siteId: [QueryArgument]!) {
  navigationNodes(navHandle: "topNav", siteId: $siteId) {
    title
    nodeUri
    id
    language
    children {
      nodeUri
      title
      nodeUri
      id
      language
    }
  }
}
